#### 创建对象
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/createObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"changing":"somestring"
,"createdAt":"somestring"
,"dataTimeOfBridge":"somestring"
,"dataTimeOfNeutron":"somestring"
,"dateFlag":"somestring"
,"name":"somestring"
,"productName":"somestring"
,"token":"somestring"
,"totalMassOfBridge":0
,"totalMassOfNeutron":0
}
 
#### 更新对象
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/updateObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"changing":"somestring"
,"createdAt":"somestring"
,"dataTimeOfBridge":"somestring"
,"dataTimeOfNeutron":"somestring"
,"dateFlag":"somestring"
,"name":"somestring"
,"productName":"somestring"
,"token":"somestring"
,"totalMassOfBridge":0
,"totalMassOfNeutron":0
}

#### 获取对象
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/getObjById
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
	"id":"somestring"
}

#### 对象列表
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/listObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json

#### 对象翻页
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/pageObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 
 "changing":"somestring"
,"createdAt":"somestring"
,"dataTimeOfBridge":"somestring"
,"dataTimeOfNeutron":"somestring"
,"dateFlag":"somestring"
,"name":"somestring"
,"productName":"somestring"
,"token":"somestring"
,"totalMassOfBridge":0
,"totalMassOfNeutron":0
}

#### 对象总数
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/count4Page
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 
 "changing":"somestring"
,"createdAt":"somestring"
,"dataTimeOfBridge":"somestring"
,"dataTimeOfNeutron":"somestring"
,"dateFlag":"somestring"
,"name":"somestring"
,"productName":"somestring"
,"token":"somestring"
,"totalMassOfBridge":0
,"totalMassOfNeutron":0
}

#### 删除对象
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/deleteObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 "id":"somestring"
}
 
#### 删除对象列表
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/deleteObjs
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 "ids":["somestring"]
}

#### 创建对象
POST http://127.0.0.1:8888/digger_assistant/minechangestatus/createObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"changing":"somestring"
,"createdAt":"somestring"
,"dataTimeOfBridge":"somestring"
,"dataTimeOfNeutron":"somestring"
,"dateFlag":"somestring"
,"name":"somestring"
,"productName":"somestring"
,"token":"somestring"
,"totalMassOfBridge":0
,"totalMassOfNeutron":0
}
