#### 创建对象
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/createObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"tokenOfBoomGroup":"somestring"
,"tokenOfMineProduct":"somestring"
,"name":"somestring"
,"token":"somestring"
}
 
#### 更新对象
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/updateObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"tokenOfBoomGroup":"somestring"
,"tokenOfMineProduct":"somestring"
,"name":"somestring"
,"token":"somestring"
}

#### 获取对象
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/getObjById
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
	"id":"somestring"
}

#### 对象列表
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/listObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json

#### 对象翻页
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/pageObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 
 "tokenOfBoomGroup":"somestring"
,"tokenOfMineProduct":"somestring"
,"name":"somestring"
,"token":"somestring"
}

#### 对象总数
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/count4Page
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 
 "tokenOfBoomGroup":"somestring"
,"tokenOfMineProduct":"somestring"
,"name":"somestring"
,"token":"somestring"
}

#### 删除对象
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/deleteObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 "id":"somestring"
}
 
#### 删除对象列表
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/deleteObjs
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 "ids":["somestring"]
}

#### 创建对象
POST http://127.0.0.1:8888/digger_assistant/productandboomgroup/createObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"tokenOfBoomGroup":"somestring"
,"tokenOfMineProduct":"somestring"
,"name":"somestring"
,"token":"somestring"
}
